openapi: 3.0.0
info:
  title: URL Shortener API
  description: A simple URL shortener API with user authentication
  version: 1.0.0
  contact:
    name: Victor
    email: victor@example.com
servers:
  - url: http://localhost:3000
    description: Local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        
    Url:
      type: object
      properties:
        id:
          type: integer
        originalUrl:
          type: string
        shortUrl:
          type: string
        clicks:
          type: integer
        
paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /urls/shorten:
    post:
      tags:
        - URL
      summary: Shorten a URL
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                originalUrl:
                  type: string
      responses:
        '200':
          description: URL shortened successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /urls:
    get:
      tags:
        - URL
      summary: List user URLs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Url'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /{shortUrl}:
    get:
      tags:
        - URL
      summary: Redirect to the original URL
      parameters:
        - name: shortUrl
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirects to the original URL
        '404':
          description: URL not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
